import { Timestamp } from "firebase/firestore";
import { Product } from "@/app/_models/product";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "mock-power-cup-tlr",
    path: "products/mock-power-cup-tlr",
    name: "MICHELIN Power Cup TLR",
    slug: "michelin-power-cup-tlr",
    brand: "MICHELIN",
    shortDescription: "Un pneu route premium pour les sorties rapides, les cyclosportives et les cyclistes qui cherchent du rendement.",
    description:
      "Pensé pour les cyclistes route exigeants, le MICHELIN Power Cup TLR met l'accent sur la vitesse, la précision et la confiance en virage. Il accompagne les sorties longues comme les objectifs de performance.",
    technicalDetails: "Tubeless Ready, usage route performance, carcasse orientée rendement et grip.",
    bikeType: ["road"],
    dimension: {
      diameter: 700,
      width: 28,
      unit: "mm",
      isoSize: "28-622",
    },
    weight: 280,
    maxPressure: 6.5,
    minPressure: 4,
    price: 7990,
    compareAtPrice: 8990,
    stock: 24,
    status: "active",
    images: [],
    tags: ["Route", "Tubeless Ready", "Premium", "Performance"],
    createdAt: Timestamp.now(),
  },
  {
    id: "mock-power-gravel",
    path: "products/mock-power-gravel",
    name: "MICHELIN Power Gravel",
    slug: "michelin-power-gravel",
    brand: "MICHELIN",
    shortDescription: "Pour les cyclistes gravel qui veulent passer de la route aux chemins sans perdre le fil.",
    description:
      "Le MICHELIN Power Gravel s'adresse aux sorties mixtes, aux aventures rapides et aux cyclistes qui veulent garder du contrôle quand le terrain change.",
    technicalDetails: "Profil gravel polyvalent, protection renforcée et rendement adapté aux terrains mixtes.",
    bikeType: ["gravel"],
    dimension: {
      diameter: 700,
      width: 40,
      unit: "mm",
      isoSize: "40-622",
    },
    weight: 450,
    maxPressure: 5,
    minPressure: 2.5,
    price: 6490,
    stock: 18,
    status: "active",
    images: [],
    tags: ["Gravel", "Aventure", "Contrôle"],
    createdAt: Timestamp.now(),
  },
  {
    id: "mock-wild-enduro",
    path: "products/mock-wild-enduro",
    name: "MICHELIN Wild Enduro Racing Line",
    slug: "michelin-wild-enduro-racing-line",
    brand: "MICHELIN",
    shortDescription: "Un choix VTT premium pour chercher l'adhérence, le contrôle et la robustesse en terrain engagé.",
    description:
      "Le MICHELIN Wild Enduro Racing Line accompagne les riders qui veulent attaquer en descente, garder de l'appui dans les passages techniques et rouler avec confiance.",
    technicalDetails: "Gomme orientée grip, carcasse renforcée, usage enduro et terrain technique.",
    bikeType: ["mountain"],
    dimension: {
      diameter: 29,
      width: 2.4,
      unit: "inches",
    },
    weight: 1100,
    maxPressure: 3,
    minPressure: 1.5,
    price: 7490,
    compareAtPrice: 8490,
    stock: 12,
    status: "active",
    images: [],
    tags: ["VTT", "Enduro", "Racing Line", "Grip"],
    createdAt: Timestamp.now(),
  },
];
